# Run the cell below to import the Python libraries

In [1]:
# Import required Python libraries
import pandas as pd
import numpy as np

# Python tools & functions

The Python functions you might need to use are the following:
- Display a DataFrame `df`: `display(df)`
- Create an empty DataFrame `df` with indices (row) "index_names" and columns "columns_names": `df = pd.DataFrame(index = index_names, columns = columns_names, dtype = float)`
`dtype = float` guarantees that the type of data in the DataFrame will be of type float.
Indices and columns can be taken from another DataFrame. 
- Read the indices of a DataFrame `df`: `df.index`
- Read the columns of a DataFrame `df`: `df.columns`
- Fill in a value from an index (row) and column of a DataFrame `df`: `df.loc[index, column] = value`
- Replace NaN values by 0 in a DataFrame `df`: `df = df.fillna(0)`
- Concatenate two DataFrames `df1` and `df2` to get `df3`:
    - Along the index: `df3 = pd.concat([df1, df2], axis = 0)`
    - Along the columns: `df3 = pd.concat([df1, df2], axis = 1)`
- Define an identity matrix `I` of size s: `I = np.identity(s)`
- Get the size of a DataFrame `df`: `len(df)`
- Inverse a DataFrame `df`: `np.linalg.inv(df)` -> /!\ this returns a `np.array`
- Convert a `np.array` to a DataFrame with specified index and columns: `pd.DataFrame(np.array, index, columns)`
- Multiply two DataFrames `df1` and `df2`: `df3 = df1 @ df2`
    - `df1` and `df2` should have matching `df1.columns` with `df2.index` for the multiplication to run
    - After the multiplication, the index of `df3` are the index of `df1` and the columns of `df3` are the columns of `df2`
    - It is therefore necessary to rename index/columns of `df3` to get the correct names
- Rename index of a DataFrame `df`: `df = df.rename(index = {initial_index_name : new_index_name})`
- Rename column of a DataFrame `df`: `df = df.rename(columns = {initial_column_name : new_column_name})`
- Diagonalize the column "column_name" of DataFrame `df`: `np.diag(df["column name"])` -> /!\ this returns a np.array
- Summing two DataFrames: `df3 = df1 + df2`. You have to make sure the DataFrames have the same sizes and indices/columns.
- Select part of a DataFrame which is a vector: `df_part = df.loc[to_select]`. `to_select` should be a list or can be indices from another DataFrame.
- Transpose a DataFrame `df`: `np.transpose(df)`
- Sum in a DataFrame `df`:
    - Along the index (which is equivalent to a column sum): `df.sum(axis = 0)`
    - Along the columns (which is equivalent to a row sum): `df.sum(axis = 1)`
- Dividing element-wise a DataFrame `df` by a `other`: (`other` can be a scalar, Series, or DataFrame)
    - Along the index: `df.div(other, axis = 0)`
    - Along the columns: `df.div(other, axis = 1)`
- Create a stacked bar chart using `df`: `df.plot(kind='barh', stacked=True)`

# 1. Importing the matrices

In [2]:
### Importing all the matrices needed
excel_document = 'matrices_exam.xlsx'

Abb = pd.read_excel(excel_document, sheet_name = 'Abb', index_col = [0]).fillna(0)

Aff_diesel = pd.read_excel(excel_document, sheet_name = 'Aff_diesel', index_col = [0]).fillna(0)
Aff_electric = pd.read_excel(excel_document, sheet_name = 'Aff_electric', index_col = [0]).fillna(0)

Abf_diesel = pd.read_excel(excel_document, sheet_name = 'Abf_diesel', index_col = [0]).fillna(0)
Abf_electric = pd.read_excel(excel_document, sheet_name = 'Abf_electric', index_col = [0]).fillna(0)

Sf_diesel = pd.read_excel(excel_document, sheet_name = 'Sf_diesel', index_col = [0]).fillna(0)
Sf_electric = pd.read_excel(excel_document, sheet_name = 'Sf_electric', index_col = [0]).fillna(0)

Sb = pd.read_excel(excel_document, sheet_name = 'Sb', index_col = [0]).fillna(0)

C = pd.read_excel(excel_document, sheet_name = 'C', index_col = [0]).fillna(0)

y_diesel = pd.read_excel(excel_document, sheet_name = 'y_diesel', index_col = [0]).fillna(0)
y_electric = pd.read_excel(excel_document, sheet_name = 'y_electric', index_col = [0]).fillna(0)

# 2. Diesel bus

Generate `A_diesel`, `S_diesel`, `d_diesel`, `Dpro_diesel`, `Dprof_diesel`

In [3]:
A_d1 = pd.concat([Aff_diesel, Abf_diesel], axis = 0)
A_diesel = pd.concat([A_d1, Abb], axis = 1)
A_diesel =A_diesel.fillna(0)



#y_diesel = pd.DataFrame(index = Aff_diesel.index, columns = "Demand", dtype = float)

In [7]:
S_diesel = pd.concat([Sf_diesel, Sb], axis = 1)
S_diesel =S_diesel.fillna(0)
display(S_diesel)

,Operation diesel bus,Assembly of diesel bus,Dismanteling of diesel bus,"Base frame, wheels and suspension",Body with windows and seats,Engine with gearbox,Fuel tank and exhaust system,Aluminium and aluminium products - tonnes,Aluminium ores and concentrates - tonnes,Basic iron and steel and of ferro-alloys and first products thereof - tonnes,...,Non-specified Petroleum Products - tonnes,Other Bituminous Coal - tonnes,Other non-metallic mineral products - tonnes,Paper and paper products - tonnes,Plastics; basic - tonnes,Refinery Feedstocks - tonnes,Refinery Gas - tonnes,Rubber and plastic products - tonnes,Sand and clay - tonnes,Steam and hot water supply services - TJ
CH4 - air - kg,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1.787807,0.068613,0.234701,...,0.186239,6.450831,0.275913,0.835843,0.207299,0.862593,0.048498,0.282013,0.004861,14.342176
CO2 - air - kg,0.56,0.0,0.0,0.0,0.0,0.0,0.0,1027.808201,204.899202,549.379634,...,41.773227,72.028615,769.996949,792.585423,220.802646,198.223167,23.630955,345.884248,1.977885,85689.217996
HFC - air - kg,0.00,0.0,0.0,0.0,0.0,0.0,0.0,4.312216,1.631413,4.738372,...,0.572536,2.053952,2.422934,11.259534,2.071034,4.848523,0.335654,10.244935,2.254895,1.010385
N2O - air - kg,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.033364,0.004402,0.005413,...,0.000254,0.002318,0.014726,0.102229,0.004380,0.001959,0.000220,0.007667,0.000036,2.318034
NMVOC - air - kg,0.00,0.0,0.0,0.0,0.0,0.0,0.0,2.454342,0.448348,0.084499,...,0.197430,0.012381,0.241331,1.779238,2.768487,1.362433,0.060390,3.289023,0.003108,8.611010
PFC - air - kg,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1015.218045,0.075168,0.968856,...,0.064630,0.049454,0.357167,1.470634,0.471882,0.431213,0.038231,0.726242,0.402505,0.194577
SF6 - air - kg,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.000310,0.000010,0.000057,...,0.000005,0.000031,0.000015,0.000053,0.000022,0.000028,0.000002,0.000091,0.000022,0.000015

In [19]:
I = np.identity(len(A_diesel.index))
I = pd.DataFrame(I, A_diesel.index, A_diesel.columns)

L_d_array = np.linalg.inv(I-A_diesel) 
L_d = pd.DataFrame(L_d_array, A_diesel.index, A_diesel.columns)

x_d = L_d@y_diesel
x_d = x_d.rename(columns = {"Demand" : "Output"})
#display(x_d)

In [10]:
e_d = S_diesel@x_d
display(e_d)

d_diesel = C@e_d
d_diesel = d_diesel.rename(columns = { "Output" : "Impact potential"})
display(d_diesel)

x_d_array = np.diag(x_d["Output"])
x_d_diag = pd.DataFrame(x_d_array, A_diesel.index, A_diesel.columns)

Dpro_diesel = C@S_diesel@x_d_diag
display(Dpro_diesel)

                        Output
CH4 - air - kg    4.850467e-03
CO2 - air - kg    7.641268e-01
HFC - air - kg    4.151748e-03
N2O - air - kg    3.603226e-06
NMVOC - air - kg  1.132554e-03
PFC - air - kg    2.164671e-03
SF6 - air - kg    2.446143e-08

                                     Impact potential
Climate change - GWP100 (kg CO2-eq)          0.893388

,Operation diesel bus,Assembly of diesel bus,Dismanteling of diesel bus,"Base frame, wheels and suspension",Body with windows and seats,Engine with gearbox,Fuel tank and exhaust system,Aluminium and aluminium products - tonnes,Aluminium ores and concentrates - tonnes,Basic iron and steel and of ferro-alloys and first products thereof - tonnes,...,Non-specified Petroleum Products - tonnes,Other Bituminous Coal - tonnes,Other non-metallic mineral products - tonnes,Paper and paper products - tonnes,Plastics; basic - tonnes,Refinery Feedstocks - tonnes,Refinery Gas - tonnes,Rubber and plastic products - tonnes,Sand and clay - tonnes,Steam and hot water supply services - TJ
Climate change - GWP100 (kg CO2-eq),0.56,0.0,0.0,0.0,0.0,0.0,0.0,0.003956,0.000323,0.006833,...,0.000356,0.004159,0.001004,0.000146,0.000722,0.002572,0.000284,0.000271,0.000014,0.015886

In [18]:
x_d_f = x_d.loc[Aff_diesel.index]
#display(x_d_f)
x_d_f_array = np.diag(x_d_f["Output"])
x_d_f_diag = pd.DataFrame(x_d_f_array, Aff_diesel.index, Aff_diesel.columns)


Dproff_diesel = C@ Sf_diesel@x_d_f_diag
display(Dproff_diesel)

,Operation diesel bus,Assembly of diesel bus,Dismanteling of diesel bus,"Base frame, wheels and suspension",Body with windows and seats,Engine with gearbox,Fuel tank and exhaust system
Climate change - GWP100 (kg CO2-eq),0.56,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
I = np.identity(len(Abb.index))
I = pd.DataFrame(I, Abb.index, Abb.columns)
L_bb_d_array = np.linalg.inv(I-Abb) 
L_bb_d = pd.DataFrame(L_bb_d_array, Abb.index, Abb.columns)

#x_d_b = x_d.loc[Abb.index]
#x_d_b_array = np.diag(x_d_b["Output"])
#x_d_b_diag = pd.DataFrame(x_d_b_array, Abb.index, Abb.columns)

M_bf_d = Abf_diesel @ x_d_f_diag

Xbf_d = L_bb_d@ M_bf_d
Dprobf_diesel = C@Sb@Xbf_d
display(Dprobf_diesel)

Dprof_diesel = Dproff_diesel+Dprobf_diesel
display(Dprof_diesel)

,Operation diesel bus,Assembly of diesel bus,Dismanteling of diesel bus,"Base frame, wheels and suspension",Body with windows and seats,Engine with gearbox,Fuel tank and exhaust system
Climate change - GWP100 (kg CO2-eq),0.285031,0.000934,0.001408,0.011275,0.03099,0.002884,0.000866

,Operation diesel bus,Assembly of diesel bus,Dismanteling of diesel bus,"Base frame, wheels and suspension",Body with windows and seats,Engine with gearbox,Fuel tank and exhaust system
Climate change - GWP100 (kg CO2-eq),0.845031,0.000934,0.001408,0.011275,0.03099,0.002884,0.000866

# 3. Electric bus

Generate `A_electric`, `S_electric`, `d_electric`, `Dpro_electric`, `Dprof_electric`.

In [40]:
A_e1 = pd.concat([Aff_electric, Abf_electric], axis = 0)
A_electric = pd.concat([A_e1, Abb], axis = 1)
A_electric =A_electric.fillna(0)

S_electric = pd.concat([Sf_electric, Sb], axis = 1)
S_electric =S_electric.fillna(0)

I = np.identity(len(A_electric.index))
I = pd.DataFrame(I, A_electric.index, A_electric.columns)

L_e_array = np.linalg.inv(I-A_electric) 
L_e = pd.DataFrame(L_e_array, A_electric.index, A_electric.columns)

x_e = L_e@y_electric
x_e = x_e.rename(columns = {"Demand" : "Output"})

e_e = S_electric@x_e
display(e_e)

d_electric = C@e_e
d_electric = d_electric.rename(columns = { "Output" : "Impact potential"})
display(d_electric)

x_e_array = np.diag(x_e["Output"])
x_e_diag = pd.DataFrame(x_e_array, A_electric.index, A_electric.columns)

Dpro_electric = C@S_electric@x_e_diag
display(Dpro_electric)

x_e_f = x_e.loc[Aff_electric.index]
#display(x_d_f)
x_e_f_array = np.diag(x_e_f["Output"])
x_e_f_diag = pd.DataFrame(x_e_f_array, Aff_electric.index, Aff_electric.columns)


Dproff_electric = C@ Sf_electric@x_e_f_diag
display(Dproff_electric)
I = np.identity(len(Abb.index))
I = pd.DataFrame(I, Abb.index, Abb.columns)
L_bb_array = np.linalg.inv(I-Abb) 
L_bb = pd.DataFrame(L_bb_array, Abb.index, Abb.columns)

#x_d_b = x_d.loc[Abb.index]
#x_d_b_array = np.diag(x_d_b["Output"])
#x_d_b_diag = pd.DataFrame(x_d_b_array, Abb.index, Abb.columns)

M_bf_e = Abf_electric @ x_e_f_diag

Xbf_e = L_bb@ M_bf_e
Dprobf_electric = C@Sb@Xbf_e
display(Dprobf_electric)

Dprof_electric = Dproff_electric+Dprobf_electric
display(Dprof_electric)

                        Output
CH4 - air - kg    1.208403e-03
CO2 - air - kg    4.925052e-01
HFC - air - kg    2.039605e-03
N2O - air - kg    4.084346e-06
NMVOC - air - kg  1.551026e-04
PFC - air - kg    2.579176e-03
SF6 - air - kg    1.500211e-08

                                     Impact potential
Climate change - GWP100 (kg CO2-eq)            0.5289

,Operation electric bus,Assembly of electric bus,Dismanteling of electric bus,"Base frame, wheels and suspension",Body with windows and seats,Electric engine with gearbox,Battery pack,Aluminium and aluminium products - tonnes,Aluminium ores and concentrates - tonnes,Basic iron and steel and of ferro-alloys and first products thereof - tonnes,...,Non-specified Petroleum Products - tonnes,Other Bituminous Coal - tonnes,Other non-metallic mineral products - tonnes,Paper and paper products - tonnes,Plastics; basic - tonnes,Refinery Feedstocks - tonnes,Refinery Gas - tonnes,Rubber and plastic products - tonnes,Sand and clay - tonnes,Steam and hot water supply services - TJ
Climate change - GWP100 (kg CO2-eq),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00517,0.000422,0.021719,...,0.000018,0.006669,0.001141,0.000102,0.000615,0.000039,0.000008,0.00024,0.000011,0.014313

,Operation electric bus,Assembly of electric bus,Dismanteling of electric bus,"Base frame, wheels and suspension",Body with windows and seats,Electric engine with gearbox,Battery pack
Climate change - GWP100 (kg CO2-eq),0.0,0.0,0.0,0.0,0.0,0.0,0.0

,Operation electric bus,Assembly of electric bus,Dismanteling of electric bus,"Base frame, wheels and suspension",Body with windows and seats,Electric engine with gearbox,Battery pack
Climate change - GWP100 (kg CO2-eq),0.446158,0.005373,0.004225,0.011275,0.03099,0.001578,0.029302

,Operation electric bus,Assembly of electric bus,Dismanteling of electric bus,"Base frame, wheels and suspension",Body with windows and seats,Electric engine with gearbox,Battery pack
Climate change - GWP100 (kg CO2-eq),0.446158,0.005373,0.004225,0.011275,0.03099,0.001578,0.029302

# 4. Export of the results as Excel files

In [41]:
A_diesel.to_excel('A_diesel.xlsx')

In [42]:
A_electric.to_excel('A_electric.xlsx')

In [43]:
S_diesel.to_excel('S_diesel.xlsx')

In [44]:
S_electric.to_excel('S_electric.xlsx')

In [45]:
d_diesel.to_excel('d_diesel.xlsx')

In [46]:
d_electric.to_excel('d_electric.xlsx')

In [ ]:
Dpro_diesel.to_excel('Dpro_diesel.xlsx')

In [ ]:
Dpro_electric.to_excel('Dpro_electric.xlsx')

In [ ]:
Dprof_diesel.to_excel('Dprof_diesel.xlsx')

In [ ]:
Dprof_electric.to_excel('Dprof_electric.xlsx')

# Last step: Zip your folder and upload it on Inspera :-)