# **Problem Set 7**

## **Problem set description**

The aim of this problem set is to take you through all stages of an LCA. Please note that it is not a complete LCA in the sense that neither all inputs and outputs nor all impact categories are considered. The problem set is based on a real-life case, however numbers and systems are simplified.

The aim of this LCA is to compare the performance of four different shopping bags:
1) Polyethylene (PE) bag, one-time usage,
2) Polyethylene (PE) bag, multiple uses possible,
3) Paper bag,
4) Biodegradable bag (manufactured from maize starch).

## **Tasks**
- Define a functional unit.
- Estimate the mass per bag option to show which uses the most and least material.
- Complete the system with system boundaries.
- List the largest and smallest emissions per bag.
- Show your results from the calculation of the midpoint level for all four bags. Highlight the best option per year.
- Show your results from the calculation of the endpoint level for all four bags. Highlight the best option per year.

## **Passing requirement**
- **At least 80 points**

**_Please run the cell below before you start the assignment_**

In [1]:
# Import required Python libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Folder for the files
files_folder = "files_PS7_V1_0/"

### In case formulas are entered in the csv files & correcting the datatypes
def convert_formulas(matrix, columns):
    for row in matrix.index:
        for column in columns:
            if type(matrix.loc[row, column]) == str:
                if " " in matrix.loc[row, column]:
                    matrix.loc[row, column] = matrix.loc[row, column].lstrip(' ')
                if "=" in matrix.loc[row, column]:
                    matrix.loc[row, column] = matrix.loc[row, column].lstrip('=')
                matrix.loc[row, column] = pd.eval(matrix.loc[row, column])
    matrix[columns] = matrix[columns].astype("float64")
    return matrix

## **1. Differences between TRACI, LC-Impact and ReCiPe** _(5 points)_

Match the best description with TRACI, LC-Impact and ReCiPe. Only **one** definition should be matched with each of the three different methods.

|Table 1||
|-|-|
|**No.**|**Description**|
|1|Midpoint level only, no weighting possible. No ionizing radiation, no land use, no water use.|
|2|Mid- and Endpoint level, weighting and normalization possible. Aggregation to single score possible.|
|3|Mid- and Endpoint level, primarily focused on ionizing radiation. Aggregation to single score not possible.|
|4|Only endpoint values available right now.|
|5|Midpoint level only. No weighting or normalization possible. Site-specific information is often provided.|

Define your answer as the variables `answer_1_TRACI`, `answer_1_LCImpact` and `answer_1_ReCiPe`. Your answer should be `answer_1_TRACI = {1}` if you think the best description of TRACI is No. 1 as given in Table 1. The 10 points are only given if all the methodologies are correctly matched with their best description!

In [3]:
answer_1_TRACI = {1}
answer_1_LCImpact = {4}
answer_1_ReCiPe = {2}

**_Run the cell under to check the format of your answer(s)_**

In [4]:
assert all (type(i) in [set] for i in [answer_1_TRACI, answer_1_LCImpact, answer_1_ReCiPe]), 'The answer(s) must be a set of values'

## **2. Cultural theory in ReCiPe & Value choices in LC-Impact** _(10 points)_

#### **2a)** Which of those below are valid in the context of ReCiPe methodology?  _(4 points)_ 

|Table 2||
|-|-|
|**No.**||
|1|Minimalist|
|2|Individualist|
|3|Optimist|
|4|Pessimist|
|5|Hierarchist|
|6|Egalitarian|

Define your answer as the variable `answer_2a` (e.g. `answer_2a = {1, 2}` if you think the correct perspectives are {1, 2}). All the perspectives must be selected to get all the points!

In [7]:
answer_2a = {2, 5, 6}

**_Run the cell under to check the format of your answer(s)_**

In [8]:
assert all (type(i) in [set] for i in [answer_2a]), 'The answer(s) must be a set of values'

#### **2b)** Match the perspectives with their main characteristics _(4 points)_ 

|Table 2||
|-|-|
|**No.**|**Description**|
|'a'|Shortest time horizon, only takes impacts that are "granted" into account.|
|'b'|Considers only direct environmental impacts, ignoring indirect and upstream/downstream impacts.|
|'c'|Focuses solely on the economic aspects, disregarding environmental and social impacts.|
|'d'|Usually used compromise, following the political targets and precautionary aspects.|
|'e'|Most precautious one, everything with a potential impact is taken into account, time horizons considered are long.|

Define your answer as the variable `answer_2b` as a set of **(perspective from ReCiPe, description)** (e.g. `answer_2b = {(1, 'c'), (2, 'd'), (4, 'a')}` if you have selected perspectives 1, 2 and 4 in question 2a) and that their respective matching descriptions are 'c', 'd' and 'a'). All the selected perspectives from question 2a must be correctly matched with their description to get all the points!

In [9]:
answer_2b = {(2, 'a'), (5, 'd'), (6, 'e')}

**_Run the cell under to check the format of your answer(s)_**

In [10]:
assert all (type(i) in [set] for i in [answer_2b]), 'The answer(s) must be a set of values'

#### **2c)** How does LC-Impact handle value choices? _(2 points)_ 

1. LC-Impact handles value choices by incorporating the same perspectives as ReCiPe.
2. LC-Impact explicitly separates short-term/certain impacts from long-term/uncertain impacts.
3. LC-Impact deals with value choices by providing a single score for all impact categories, without any separation or distinction between them.
4. LC-Impact handles value choices by focusing only on short-term impacts and disregarding any potential long-term or uncertain impacts.
5. The separation of impacts in LC-Impact is made in an additive way, allowing users to combine short-term and long-term impacts if desired.

Define your answer as the variable `answer_2c` (e.g. `answer_2c = {1}` if you think the correct statement is statement {1} or `answer_2c = {1, 2}` if you think the correct statements are statements {1, 2}).

In [11]:
answer_2c = {2}

**_Run the cell under to check the format of your answer(s)_**

In [12]:
assert all (type(i) in [set] for i in [answer_2c]), 'The answer(s) must be a set of values'

## **3. Choice of functional unit(s)** _(5 points)_

One option for a functional unit is to just compare the bags with each other. That might not be the best functional unit though. It is assumed that an average customer goes 45 times a year to the supermarket and buys on average 200 l of goods each time, which one(s) of the following options can be a good functional unit? 

1. Carrying capacity of 200 liters of goods for one shopping trip
2. Total number of shopping bags required to carry 200 liters of goods for 45 shopping trips per year
3. Cost of the shopping bags needed for 45 shopping trips per year
4. Total weight of bags needed to carry 200 liters of goods for 45 shopping trips per year
5. Total volume of goods carried by the bags over 45 shopping trips per year

Define your answer as the variable `answer_3` (e.g. `answer_3 = {1}` if you think the correct statement is statement {1} or `answer_3 = {1, 2}` if you think the correct statements are statements {1, 2}).

In [13]:
answer_3 = {2, 4}

**_Run the cell under to check the format of your answer(s)_**

In [14]:
assert all (type(i) in [set] for i in [answer_3]), 'The answer(s) must be a set of values'

## **4. Mass of materials used for the bags over 1 year** _(15 points)_

Run the cell below to import the table containing informations about the four types of bags.

In [17]:
bags_material = convert_formulas(pd.read_csv(files_folder + 'bags_material.csv', sep = ',', index_col = [0]), ['Total number of bags used over 1 year (pc)', 'Total mass of used bags over 1 year (kg)'])

# Convert relevant columns to numeric data type
bags_material['Volume (L)'] = pd.to_numeric(bags_material['Volume (L)'], errors='coerce')
bags_material['Usable times'] = pd.to_numeric(bags_material['Usable times'], errors='coerce')
bags_material['Mass per bag (g)'] = pd.to_numeric(bags_material['Mass per bag (g)'], errors='coerce')

display(bags_material)

,Material,Mass per bag (g),Volume (L),Usable times,Total number of bags used over 1 year (pc),Total mass of used bags over 1 year (kg)
One-time PE bag,high density PE,5.04,10.0,1,900.000000,4.536000
Multiple-use PE bag,high density PE,43.00,25.2,3,119.047619,5.119048
Paper bag,recycled paper,51.00,22.1,1,407.239819,20.769231
Biodegradable bag,50% corn starch + 50% Polycaprolacton,16.00,27.0,1,333.333333,5.333333

Assuming the following:
- An average customer goes 45 times a year to the supermarket and buys on average 200 l of goods each time
- The re-usable bags are used 3 times.

How many bags are used to pack the shopping volume of one year? What is the mass of the used bags per option?
Fill in the two last columns of the table `bags_material` to answer the questions. For that, you have two options: 
- Option 1: filling in csv file located in the **files_PS7_V1_0** folder and save the csv files by using "ctrl+s". **If you are calculating some numbers, you should enter the formulas in the table.**
- Option 2: filling in the table in the two cells below containing the comments # Fill in column 'Total number of bags used over 1 year (pc)' and # Fill in column 'Total mass of used bags over 1 year (kg)'

In [18]:
display(bags_material)

,Material,Mass per bag (g),Volume (L),Usable times,Total number of bags used over 1 year (pc),Total mass of used bags over 1 year (kg)
One-time PE bag,high density PE,5.04,10.0,1,900.000000,4.536000
Multiple-use PE bag,high density PE,43.00,25.2,3,119.047619,5.119048
Paper bag,recycled paper,51.00,22.1,1,407.239819,20.769231
Biodegradable bag,50% corn starch + 50% Polycaprolacton,16.00,27.0,1,333.333333,5.333333

**_Run the cell under to check the format of your answer(s)_**

In [19]:
assert bags_material['Total number of bags used over 1 year (pc)'].isnull().values.any() == False, 'There are still NaN values in the matrix'

In [22]:
print('hei')

hei

**_Run the cell under to check the format of your answer(s)_**

In [20]:
assert bags_material['Total mass of used bags over 1 year (kg)'].isnull().values.any() == False, 'There are still NaN values in the matrix'

Which option uses most material? Which option uses least material? 
1. One-time PE bag
2. Multiple-use PE bag
3. Paper bag
4. Biodegradable bag

Define your answer as the variables `answer_4_most` and `answer_4_least` (e.g. `answer_4_most = {1}` if you think the correct bag is the "1. One-time PE bag").

In [23]:
answer_4_most = {3}
answer_4_least = {1}

**_Run the cell under to check the format of your answer(s)_**

In [24]:
assert all (type(i) in [set] for i in [answer_4_most, answer_4_least]), 'The answer(s) must be a set of values'

## **5. System boundaries** _(10 points)_

Complete the system boundaries for the one-time PE bag from the description below.

The life cycle consists of four major stages: (1) production of PEHD, (2) fabrication of bags, (3) transport to supermarket and (4) disposal. In the production for PEHD the first step is extraction of oil and refining of oil, followed by the production of PEHD granules. This requires as an additional input electricity. In the fabrication stage the transported PEHD granules are formed into bags through extrusion, which again requires electricity. In order to print some text on the bag, pigments have to be produced (which requires the production of TiO2, CaCO3 and LLDPE (linear low-density polyethylene) as inputs). Furthermore glue and ink have to be produced for use in the fabrication of the bags. After production the bags are transported by ship and truck to the supermarket. The end-of life (neglect the use phase between supermarket and end-of life) involves transport to the incineration facility (43% of the bags) where energy is recovered, or to an incineration facility without energy recovery (6%), or they are transported to a landfill (51%).

|Table 3||
|-|-|
|**No.**||
|1|Electricity|
|2|Extraction of oil|
|3|Landfill|
|4|Ink|
|5|Pigment production|
|6|Refining of oil|

<img src="files_PS7_V1_0/PS7_V1_0_2023_question5.png" width="500">

Define your answer as the variables `answer_5_A`, `answer_5_B`, `answer_5_C`, `answer_5_D`, `answer_5_E`, `answer_5_F`. Your answer should be `answer_1a_A = {1}` if you think the correct name for A is "1) Electricity". The points are only given if all the names are correctly placed!

In [25]:
answer_5_A = {2}
answer_5_B = {6}
answer_5_C = {1}
answer_5_D = {5}
answer_5_E = {4}
answer_5_F = {3}

**_Run the cell under to check the format of your answer(s)_**

In [26]:
assert all (type(i) in [set] for i in [answer_5_A, answer_5_B, answer_5_C, answer_5_D, answer_5_E, answer_5_F]), 'The answer(s) must be a set of values'

## **6. Life Cycle Inventory** _(15 points)_

We give you the vectors of total stressors for the four types of bags: `e_onetime`, `e_multuse`, `e_paper` and `e_bio` which were obtained by calculating $e_\text{type of bag} = S_\text{type of bag} * L_\text{type of bag} * y_\text{type of bag}$ representing the life cycle of each type of bag and where $y_\text{type of bag}$ is a vector of 1 for the specific type of bag and 0 for all other processes. Therefore, each $e_\text{type of bag}$ can be read by "total stressors for 1 bag of the type $_\text{type of bag}$".

In [27]:
e_onetime = pd.read_csv(files_folder + 'e_onetime.csv', sep = ',', index_col = [0])
e_multuse = pd.read_csv(files_folder + 'e_multuse.csv', sep = ',', index_col = [0])
e_paper = pd.read_csv(files_folder + 'e_paper.csv', sep = ',', index_col = [0])
e_bio = pd.read_csv(files_folder + 'e_bio.csv', sep = ',', index_col = [0])

display(e_onetime)
display(e_multuse)
display(e_paper)
display(e_bio)

                                   One-time PE bag
﻿
Ammonia (NH3), air (kg)               4.201780e-09
1,3-butadiene, air (kg)               7.238000e-09
1,3-butadiene, water (kg)             8.555560e-11
Zinc, air (kg)                        2.156000e-08
Zinc, water (kg)                      1.457870e-07
Carbon dioxide, air (kg)              1.728222e-02
Methane, fossil, air (kg)             3.766440e-05
CFC-113, air (kg)                     5.612440e-08
Nitrous oxide, air (kg)               1.134470e-07
Nitrogen oxide, air (kg)              4.637110e-05
Particulates, < 10 um, air (kg)       3.285330e-05
Sulfur oxides, air (kg)               6.004000e-05
Phosphorus pentoxide, water (kg)      4.551560e-12
Strontium-90 (Sr-90), water (kBq)     9.394000e-05

                                   Multiple-use PE bag
﻿
Ammonia (NH3), air (kg)                   1.650640e-08
1,3-butadiene, air (kg)                   3.159530e-08
1,3-butadiene, water (kg)                 1.205930e-12
Zinc, air (kg)                            3.569540e-08
Zinc, water (kg)                          4.051910e-07
Carbon dioxide, air (kg)                  3.791615e-02
Methane, fossil, air (kg)                 1.314460e-04
CFC-113, air (kg)                         2.894220e-11
Nitrous oxide, air (kg)                   1.070860e-07
Nitrogen oxide, air (kg)                  1.166130e-04
Particulates, < 10 um, air (kg)           8.043530e-05
Sulfur oxides, air (kg)                   1.052770e-04
Phosphorus pentoxide, water (kg)          1.266220e-11
Strontium-90 (Sr-90), water (kBq)         9.249450e-05

                                      Paper bag
﻿
Ammonia (NH3), air (kg)            6.496060e-07
1,3-butadiene, air (kg)            5.086280e-07
1,3-butadiene, water (kg)          2.505560e-10
Zinc, air (kg)                     2.505560e-07
Zinc, water (kg)                   1.092420e-08
Carbon dioxide, air (kg)           4.584278e-02
Methane, fossil, air (kg)          3.958780e-04
CFC-113, air (kg)                  2.505560e-11
Nitrous oxide, air (kg)            1.368030e-06
Nitrogen oxide, air (kg)           1.819030e-04
Particulates, < 10 um, air (kg)    1.182620e-05
Sulfur oxides, air (kg)            7.539500e-05
Phosphorus pentoxide, water (kg)   3.232170e-11
Strontium-90 (Sr-90), water (kBq)  1.949322e-03

                                   Biodegradable bag
﻿
Ammonia (NH3), air (kg)                 7.338890e-06
1,3-butadiene, air (kg)                 2.465830e-07
1,3-butadiene, water (kg)               1.222220e-10
Zinc, air (kg)                          4.583330e-08
Zinc, water (kg)                        6.355560e-09
Carbon dioxide, air (kg)                4.225000e-02
Methane, fossil, air (kg)               1.680560e-04
CFC-113, air (kg)                       3.055560e-09
Nitrous oxide, air (kg)                 3.727780e-06
Nitrogen oxide, air (kg)                1.527780e-04
Particulates, < 10 um, air (kg)         6.386110e-06
Sulfur oxides, air (kg)                 9.686110e-05
Phosphorus pentoxide, water (kg)        8.219440e-12
Strontium-90 (Sr-90), water (kBq)       8.525000e-05

What are the largest emissions for the biodegrable bag? What are the smallest emissions for the paper bag?

Define your answer as the variables `answer_6_largest_biobag` and `answer_6_smallest_paper`. Your answer should be `answer_6_largest_biobag = {'Ammonia (NH3), air (g)'}` if you think 'Ammonia (NH3), air (g)' is the largest emissions for the biodegradable bag. You need to copy exactly the name from the table to be sure the answer is checked correctly in the autograding system.

In [28]:
answer_6_largest_biobag = {'Carbon dioxide, air (kg)'}
answer_6_smallest_paper = {'CFC-113, air (kg)'}

**_Run the cell under to check the format of your answer(s)_**

In [29]:
assert all (type(i) in [set] for i in [answer_6_largest_biobag, answer_6_smallest_paper]), 'The answer(s) must be a set of values'
assert all (list(i)[0] in e_onetime.index for i in [answer_6_largest_biobag, answer_6_smallest_paper]), 'The answer(s) must be one of the stressors listed in the vectors of total stressors - be careful with copy-pasting it correctly'

## **7. LCIA for the four different options** _(40 points)_

### **7a)** Midpoint level _(20 points)_

We define the total number of used bags over 1 year as `n_onetime`, `n_multuse`, `n_paper` and `n_bio`. They are retrieved for you from the table `bags_material` in the cell under.

In [30]:
n_onetime = pd.DataFrame(bags_material.loc['One-time PE bag', 'Total number of bags used over 1 year (pc)'], index = ['One-time PE bag'], columns = ['Total number of bags used over 1 year (pc)'])
n_multuse = pd.DataFrame(bags_material.loc['Multiple-use PE bag', 'Total number of bags used over 1 year (pc)'], index = ['Multiple-use PE bag'], columns = ['Total number of bags used over 1 year (pc)'])
n_paper = pd.DataFrame(bags_material.loc['Paper bag', 'Total number of bags used over 1 year (pc)'], index = ['Paper bag'], columns = ['Total number of bags used over 1 year (pc)'])
n_bio = pd.DataFrame(bags_material.loc['Biodegradable bag', 'Total number of bags used over 1 year (pc)'], index = ['Biodegradable bag'], columns = ['Total number of bags used over 1 year (pc)'])

We import the three characterization matrices, one for each perspective.

In [31]:
C_i = pd.read_csv(files_folder + 'C_i.csv', sep = ',', index_col = [0]).astype(float).fillna(0) # Midpoint Characterization Individualist
C_e = pd.read_csv(files_folder + 'C_e.csv', sep = ',', index_col = [0]).astype(float).fillna(0) # Midpoint Characterization Egalitarian
C_h = pd.read_csv(files_folder + 'C_h.csv', sep = ',', index_col = [0]).astype(float).fillna(0) # Midpoint Characterization Hierarchist

Calculate the midpoint impacts for individualist perspective for the total number of used bags over 1 year for each type of bag: `d_mid_i_onetime`, `d_mid_i_multuse`, `d_mid_i_paper` and `d_mid_i_bio`. Rename their columns as "Impacts - Individualist".

In [42]:
d_mid_i_onetime = C_i @ e_onetime @ n_onetime
d_mid_i_onetime = d_mid_i_onetime.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Individualist'})
display(d_mid_i_onetime)

d_mid_i_multuse = C_i @ e_multuse @ n_multuse
d_mid_i_multuse = d_mid_i_multuse.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Individualist'})
display(d_mid_i_multuse)

d_mid_i_paper = C_i @ e_paper @ n_paper
d_mid_i_paper = d_mid_i_paper.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Individualist'})
display(d_mid_i_paper)

d_mid_i_bio = C_i @ e_bio @ n_bio
d_mid_i_bio = d_mid_i_bio.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Individualist'})
display(d_mid_i_bio)

                                            Impacts - Individualist
﻿
Freshwater eutrophication (kg P eq)                    1.802418e-09
Marine eutrophication (kg N eq)                        1.627974e-03
Climate change (kg CO2 eq)                             1.835451e+01
Ozone depletion (kg CFC-11 eq)                         5.051196e-05
Terrestrial acidification (kg SO2 eq)                  7.449318e-02
Photochemical oxidant formation (kg NMVOC)             4.733031e-03
Particulate matter formation (kg PM10 eq)              4.955786e-02
Ionising radiation (kg U235 eq)                        1.630529e-05
Agricultural land occupation (m2a)                     0.000000e+00
Urban land occupation (m2a)                            0.000000e+00
Natural land transformation (m2a)                      0.000000e+00
Water depletion (m3)                                   0.000000e+00
Metal depletion (kg Fe eq)                             0.000000e+00
Fossil depletion (kg oil eq)                           0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                  9.904963e-04
Human toxicity (kg 1,4-DB eq)                          5.031807e-04
Marine ecotoxicity (kg 1,4-DB eq)                      5.819127e-04
Terrestrial ecotoxicity (kg 1,4-DB eq)                 6.896801e-05

                                            Impacts - Individualist
﻿
Freshwater eutrophication (kg P eq)                    6.632581e-10
Marine eutrophication (kg N eq)                        5.415983e-04
Climate change (kg CO2 eq)                             5.644214e+00
Ozone depletion (kg CFC-11 eq)                         3.445500e-09
Terrestrial acidification (kg SO2 eq)                  1.933931e-02
Photochemical oxidant formation (kg NMVOC)             1.179642e-03
Particulate matter formation (kg PM10 eq)              1.513701e-02
Ionising radiation (kg U235 eq)                        2.123597e-06
Agricultural land occupation (m2a)                     0.000000e+00
Urban land occupation (m2a)                            0.000000e+00
Natural land transformation (m2a)                      0.000000e+00
Water depletion (m3)                                   0.000000e+00
Metal depletion (kg Fe eq)                             0.000000e+00
Fossil depletion (kg oil eq)                           0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                  3.635050e-04
Human toxicity (kg 1,4-DB eq)                          1.020566e-04
Marine ecotoxicity (kg 1,4-DB eq)                      1.859900e-04
Terrestrial ecotoxicity (kg 1,4-DB eq)                 1.510391e-05

                                            Impacts - Individualist
﻿
Freshwater eutrophication (kg P eq)                    5.791581e-09
Marine eutrophication (kg N eq)                        2.913386e-03
Climate change (kg CO2 eq)                             3.043772e+01
Ozone depletion (kg CFC-11 eq)                         1.020364e-08
Terrestrial acidification (kg SO2 eq)                  6.752858e-02
Photochemical oxidant formation (kg NMVOC)             4.415550e-03
Particulate matter formation (kg PM10 eq)              2.733872e-02
Ionising radiation (kg U235 eq)                        1.530979e-04
Agricultural land occupation (m2a)                     0.000000e+00
Urban land occupation (m2a)                            0.000000e+00
Natural land transformation (m2a)                      0.000000e+00
Water depletion (m3)                                   0.000000e+00
Metal depletion (kg Fe eq)                             0.000000e+00
Fossil depletion (kg oil eq)                           0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                  5.601394e-05
Human toxicity (kg 1,4-DB eq)                          2.456031e-03
Marine ecotoxicity (kg 1,4-DB eq)                      1.001910e-03
Terrestrial ecotoxicity (kg 1,4-DB eq)                 3.626698e-04

                                            Impacts - Individualist
﻿
Freshwater eutrophication (kg P eq)                    1.205518e-09
Marine eutrophication (kg N eq)                        2.211173e-03
Climate change (kg CO2 eq)                             1.848245e+01
Ozone depletion (kg CFC-11 eq)                         1.018520e-06
Terrestrial acidification (kg SO2 eq)                  6.210890e-02
Photochemical oxidant formation (kg NMVOC)             3.301810e-03
Particulate matter formation (kg PM10 eq)              2.057264e-02
Ionising radiation (kg U235 eq)                        5.480353e-06
Agricultural land occupation (m2a)                     0.000000e+00
Urban land occupation (m2a)                            0.000000e+00
Natural land transformation (m2a)                      0.000000e+00
Water depletion (m3)                                   0.000000e+00
Metal depletion (kg Fe eq)                             0.000000e+00
Fossil depletion (kg oil eq)                           0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                  1.930368e-05
Human toxicity (kg 1,4-DB eq)                          6.264412e-04
Marine ecotoxicity (kg 1,4-DB eq)                      1.543752e-04
Terrestrial ecotoxicity (kg 1,4-DB eq)                 5.430206e-05

**_Run the cell under to check the format of your answer(s)_**

In [43]:
assert (d_mid_i_onetime.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_i_multuse.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_i_paper.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_i_bio.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_i_onetime.columns == ['Impacts - Individualist']).all(), 'The columns do not correspond'
assert (d_mid_i_multuse.columns == ['Impacts - Individualist']).all(), 'The columns do not correspond'
assert (d_mid_i_paper.columns == ['Impacts - Individualist']).all(), 'The columns do not correspond'
assert (d_mid_i_bio.columns == ['Impacts - Individualist']).all(), 'The columns do not correspond'

Calculate the midpoint impacts for egalitarian perspective for the total number of used bags over 1 year for each type of bag: `d_mid_e_onetime`, `d_mid_e_multuse`, `d_mid_e_paper` and `d_mid_e_bio`. Rename their columns as "Impacts - Egalitarian".

In [45]:
d_mid_e_onetime = C_e @ e_onetime @ n_onetime
d_mid_e_onetime = d_mid_e_onetime.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Egalitarian'})
display(d_mid_e_onetime)

d_mid_e_multuse = C_e @ e_multuse @ n_multuse
d_mid_e_multuse = d_mid_e_multuse.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Egalitarian'})
display(d_mid_e_multuse)

d_mid_e_paper = C_e @ e_paper @ n_paper
d_mid_e_paper = d_mid_e_paper.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Egalitarian'})
display(d_mid_e_paper)

d_mid_e_bio = C_e @ e_bio @ n_bio
d_mid_e_bio = d_mid_e_bio.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Egalitarian'})
display(d_mid_e_bio)

                                            Impacts - Egalitarian
﻿
Freshwater eutrophication (kg P eq)                  1.802418e-09
Marine eutrophication (kg N eq)                      1.627974e-03
Climate change (kg CO2 eq)                           1.596363e+01
Ozone depletion (kg CFC-11 eq)                       5.051196e-05
Terrestrial acidification (kg SO2 eq)                8.367806e-02
Photochemical oxidant formation (kg NMVOC)           4.733031e-03
Particulate matter formation (kg PM10 eq)            4.955786e-02
Ionising radiation (kg U235 eq)                      1.630529e-05
Agricultural land occupation (m2a)                   0.000000e+00
Urban land occupation (m2a)                          0.000000e+00
Natural land transformation (m2a)                    0.000000e+00
Water depletion (m3)                                 0.000000e+00
Metal depletion (kg Fe eq)                           0.000000e+00
Fossil depletion (kg oil eq)                         0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                1.035204e-03
Human toxicity (kg 1,4-DB eq)                        6.546010e-02
Marine ecotoxicity (kg 1,4-DB eq)                    2.770495e-01
Terrestrial ecotoxicity (kg 1,4-DB eq)               1.118032e-03

                                            Impacts - Egalitarian
﻿
Freshwater eutrophication (kg P eq)                  6.632581e-10
Marine eutrophication (kg N eq)                      5.415983e-04
Climate change (kg CO2 eq)                           4.634714e+00
Ozone depletion (kg CFC-11 eq)                       3.445500e-09
Terrestrial acidification (kg SO2 eq)                2.239523e-02
Photochemical oxidant formation (kg NMVOC)           1.179642e-03
Particulate matter formation (kg PM10 eq)            1.513701e-02
Ionising radiation (kg U235 eq)                      2.123597e-06
Agricultural land occupation (m2a)                   0.000000e+00
Urban land occupation (m2a)                          0.000000e+00
Natural land transformation (m2a)                    0.000000e+00
Water depletion (m3)                                 0.000000e+00
Metal depletion (kg Fe eq)                           0.000000e+00
Fossil depletion (kg oil eq)                         0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                3.732998e-04
Human toxicity (kg 1,4-DB eq)                        1.857808e-02
Marine ecotoxicity (kg 1,4-DB eq)                    8.630404e-02
Terrestrial ecotoxicity (kg 1,4-DB eq)               2.448476e-04

                                            Impacts - Egalitarian
﻿
Freshwater eutrophication (kg P eq)                  5.791581e-09
Marine eutrophication (kg N eq)                      2.913386e-03
Climate change (kg CO2 eq)                           1.997952e+01
Ozone depletion (kg CFC-11 eq)                       1.020364e-08
Terrestrial acidification (kg SO2 eq)                8.406387e-02
Photochemical oxidant formation (kg NMVOC)           4.415550e-03
Particulate matter formation (kg PM10 eq)            2.733872e-02
Ionising radiation (kg U235 eq)                      1.530979e-04
Agricultural land occupation (m2a)                   0.000000e+00
Urban land occupation (m2a)                          0.000000e+00
Natural land transformation (m2a)                    0.000000e+00
Water depletion (m3)                                 0.000000e+00
Metal depletion (kg Fe eq)                           0.000000e+00
Fossil depletion (kg oil eq)                         0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                2.909715e-04
Human toxicity (kg 1,4-DB eq)                        1.941561e-01
Marine ecotoxicity (kg 1,4-DB eq)                    5.559605e-01
Terrestrial ecotoxicity (kg 1,4-DB eq)               5.879195e-03

                                            Impacts - Egalitarian
﻿
Freshwater eutrophication (kg P eq)                  1.205518e-09
Marine eutrophication (kg N eq)                      2.211173e-03
Climate change (kg CO2 eq)                           1.470194e+01
Ozone depletion (kg CFC-11 eq)                       1.018520e-06
Terrestrial acidification (kg SO2 eq)                7.551429e-02
Photochemical oxidant formation (kg NMVOC)           3.301810e-03
Particulate matter formation (kg PM10 eq)            2.057264e-02
Ionising radiation (kg U235 eq)                      5.480353e-06
Agricultural land occupation (m2a)                   0.000000e+00
Urban land occupation (m2a)                          0.000000e+00
Natural land transformation (m2a)                    0.000000e+00
Water depletion (m3)                                 0.000000e+00
Metal depletion (kg Fe eq)                           0.000000e+00
Fossil depletion (kg oil eq)                         0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                5.448385e-05
Human toxicity (kg 1,4-DB eq)                        2.964730e-02
Marine ecotoxicity (kg 1,4-DB eq)                    8.515198e-02
Terrestrial ecotoxicity (kg 1,4-DB eq)               8.802838e-04

**_Run the cell under to check the format of your answer(s)_**

In [46]:
assert (d_mid_e_onetime.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_e_multuse.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_e_paper.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_e_bio.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_e_onetime.columns == ['Impacts - Egalitarian']).all(), 'The columns do not correspond'
assert (d_mid_e_multuse.columns == ['Impacts - Egalitarian']).all(), 'The columns do not correspond'
assert (d_mid_e_paper.columns == ['Impacts - Egalitarian']).all(), 'The columns do not correspond'
assert (d_mid_e_bio.columns == ['Impacts - Egalitarian']).all(), 'The columns do not correspond'

Calculate the midpoint impacts for egalitarian perspective for the total number of used bags over 1 year for each type of bag: `d_mid_h_onetime`, `d_mid_h_multuse`, `d_mid_h_paper` and `d_mid_h_bio`. Rename their columns as "Impacts - Hierarchist".

In [47]:
d_mid_h_onetime = C_h @ e_onetime @ n_onetime
d_mid_h_onetime = d_mid_h_onetime.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Hierarchist'})
display(d_mid_h_onetime)

d_mid_h_multuse = C_h @ e_multuse @ n_multuse
d_mid_h_multuse = d_mid_h_multuse.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Hierarchist'})
display(d_mid_h_multuse)

d_mid_h_paper = C_h @ e_paper @ n_paper
d_mid_h_paper = d_mid_h_paper.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Hierarchist'})
display(d_mid_h_paper)

d_mid_h_bio = C_h @ e_bio @ n_bio
d_mid_h_bio = d_mid_h_bio.rename(columns = {'Total number of bags used over 1 year (pc)' : 'Impacts - Hierarchist'})
display(d_mid_h_bio)

                                            Impacts - Hierarchist
﻿
Freshwater eutrophication (kg P eq)                  1.802418e-09
Marine eutrophication (kg N eq)                      1.627974e-03
Climate change (kg CO2 eq)                           1.674151e+01
Ozone depletion (kg CFC-11 eq)                       5.051196e-05
Terrestrial acidification (kg SO2 eq)                7.741630e-02
Photochemical oxidant formation (kg NMVOC)           4.733031e-03
Particulate matter formation (kg PM10 eq)            4.955786e-02
Ionising radiation (kg U235 eq)                      1.630529e-05
Agricultural land occupation (m2a)                   0.000000e+00
Urban land occupation (m2a)                          0.000000e+00
Natural land transformation (m2a)                    0.000000e+00
Water depletion (m3)                                 0.000000e+00
Metal depletion (kg Fe eq)                           0.000000e+00
Fossil depletion (kg oil eq)                         0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                9.904963e-04
Human toxicity (kg 1,4-DB eq)                        1.474969e-02
Marine ecotoxicity (kg 1,4-DB eq)                    1.222731e-03
Terrestrial ecotoxicity (kg 1,4-DB eq)               6.896801e-05

                                            Impacts - Hierarchist
﻿
Freshwater eutrophication (kg P eq)                  6.632581e-10
Marine eutrophication (kg N eq)                      5.415983e-04
Climate change (kg CO2 eq)                           4.908856e+00
Ozone depletion (kg CFC-11 eq)                       3.445500e-09
Terrestrial acidification (kg SO2 eq)                2.031199e-02
Photochemical oxidant formation (kg NMVOC)           1.179642e-03
Particulate matter formation (kg PM10 eq)            1.513701e-02
Ionising radiation (kg U235 eq)                      2.123597e-06
Agricultural land occupation (m2a)                   0.000000e+00
Urban land occupation (m2a)                          0.000000e+00
Natural land transformation (m2a)                    0.000000e+00
Water depletion (m3)                                 0.000000e+00
Metal depletion (kg Fe eq)                           0.000000e+00
Fossil depletion (kg oil eq)                         0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                3.635050e-04
Human toxicity (kg 1,4-DB eq)                        3.917510e-03
Marine ecotoxicity (kg 1,4-DB eq)                    3.849332e-04
Terrestrial ecotoxicity (kg 1,4-DB eq)               1.510391e-05

                                            Impacts - Hierarchist
﻿
Freshwater eutrophication (kg P eq)                  5.791581e-09
Marine eutrophication (kg N eq)                      2.913386e-03
Climate change (kg CO2 eq)                           2.286552e+01
Ozone depletion (kg CFC-11 eq)                       1.020364e-08
Terrestrial acidification (kg SO2 eq)                7.283574e-02
Photochemical oxidant formation (kg NMVOC)           4.415550e-03
Particulate matter formation (kg PM10 eq)            2.733872e-02
Ionising radiation (kg U235 eq)                      1.530979e-04
Agricultural land occupation (m2a)                   0.000000e+00
Urban land occupation (m2a)                          0.000000e+00
Natural land transformation (m2a)                    0.000000e+00
Water depletion (m3)                                 0.000000e+00
Metal depletion (kg Fe eq)                           0.000000e+00
Fossil depletion (kg oil eq)                         0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                5.601394e-05
Human toxicity (kg 1,4-DB eq)                        5.292546e-02
Marine ecotoxicity (kg 1,4-DB eq)                    2.311711e-03
Terrestrial ecotoxicity (kg 1,4-DB eq)               3.626698e-04

                                            Impacts - Hierarchist
﻿
Freshwater eutrophication (kg P eq)                  1.205518e-09
Marine eutrophication (kg N eq)                      2.211173e-03
Climate change (kg CO2 eq)                           1.586034e+01
Ozone depletion (kg CFC-11 eq)                       1.018520e-06
Terrestrial acidification (kg SO2 eq)                6.679902e-02
Photochemical oxidant formation (kg NMVOC)           3.301810e-03
Particulate matter formation (kg PM10 eq)            2.057264e-02
Ionising radiation (kg U235 eq)                      5.480353e-06
Agricultural land occupation (m2a)                   0.000000e+00
Urban land occupation (m2a)                          0.000000e+00
Natural land transformation (m2a)                    0.000000e+00
Water depletion (m3)                                 0.000000e+00
Metal depletion (kg Fe eq)                           0.000000e+00
Fossil depletion (kg oil eq)                         0.000000e+00
Freshwater ecotoxicity (kg 1,4-DB eq)                1.930368e-05
Human toxicity (kg 1,4-DB eq)                        8.234954e-03
Marine ecotoxicity (kg 1,4-DB eq)                    3.548543e-04
Terrestrial ecotoxicity (kg 1,4-DB eq)               5.430206e-05

**_Run the cell under to check the format of your answer(s)_**

In [48]:
assert (d_mid_h_onetime.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_h_multuse.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_h_paper.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_h_bio.index == ['Freshwater eutrophication (kg P eq)', 'Marine eutrophication (kg N eq)', 'Climate change (kg CO2 eq)', 'Ozone depletion (kg CFC-11 eq)', 'Terrestrial acidification (kg SO2 eq)', 'Photochemical oxidant formation (kg NMVOC)', 'Particulate matter formation (kg PM10 eq)', 'Ionising radiation (kg U235 eq)', 'Agricultural land occupation (m2a)', 'Urban land occupation (m2a)', 'Natural land transformation (m2a)', 'Water depletion (m3)', 'Metal depletion (kg Fe eq)', 'Fossil depletion (kg oil eq)', 'Freshwater ecotoxicity (kg 1,4-DB eq)', 'Human toxicity (kg 1,4-DB eq)', 'Marine ecotoxicity (kg 1,4-DB eq)', 'Terrestrial ecotoxicity (kg 1,4-DB eq)']).all(), 'The index do not correspond'
assert (d_mid_h_onetime.columns == ['Impacts - Hierarchist']).all(), 'The columns do not correspond'
assert (d_mid_h_multuse.columns == ['Impacts - Hierarchist']).all(), 'The columns do not correspond'
assert (d_mid_h_paper.columns == ['Impacts - Hierarchist']).all(), 'The columns do not correspond'
assert (d_mid_h_bio.columns == ['Impacts - Hierarchist']).all(), 'The columns do not correspond'

Comparing the human toxicity potential in the hierarchist perspective, which option performs best over the whole year? How about climate change potential in the individualist perspective? How about freshwater eutrophication in the egalitarian perspective?
1. One-time PE bag
2. Multiple-use PE bag
3. Paper bag
4. Biodegradable bag

Define your answer as the variables `answer_7a_humantox`, `answer_7a_gwp` and `answer_7a_fresheutr`. Your answer should be `answer_7a_humantox = {'1'}` if you think the "1. One-time PE bag" performs best for human toxicity over the whole year.

In [53]:
answer_7a_humantox = {'2'}
answer_7a_gwp = {'2'}
answer_7a_fresheutr = {'2'}

**_Run the cell under to check the format of your answer(s)_**

In [54]:
assert all (type(i) in [set] for i in [answer_7a_humantox, answer_7a_gwp, answer_7a_fresheutr]), 'The answer(s) must be a set of values'

#### **7b)** Endpoint level _(20 points)_

We look at two endpoint impacts (human health in DALY and ecosystems in species.yr) for all four bag options and the three perspectives. We give you the matrices `P_i`, `P_e` and `P_h` (of dimensions endpoint categories x midpoint categories) which are used for converting midpoint impacts to the two endpoint impacts (human health in DALY and ecosystems in species.yr).

In [55]:
P_i = pd.read_csv(files_folder + 'P_i.csv', sep = ',', index_col = [0]).astype(float).fillna(0) # "Midpoint to Endpoint" Conversion - Individualist
P_e = pd.read_csv(files_folder + 'P_e.csv', sep = ',', index_col = [0]).astype(float).fillna(0) # "Midpoint to Endpoint" Conversion - Egalitarian
P_h = pd.read_csv(files_folder + 'P_h.csv', sep = ',', index_col = [0]).astype(float).fillna(0) # "Midpoint to Endpoint" Conversion - Hierarchist

Calculate the endpoint impacts for individualist perspective for the total number of used bags over 1 year for each type of bag: `d_end_i_onetime`, `d_end_i_multuse`, `d_end_i_paper` and `d_end_i_bio`.

In [57]:
d_end_i_onetime = P_i @ d_mid_i_onetime
display(d_end_i_onetime)

d_end_i_multuse = P_i @ d_mid_i_multuse
display(d_end_i_multuse)

d_end_i_paper = P_i @ d_mid_i_paper
display(d_end_i_paper)

d_end_i_bio = P_i @ d_mid_i_bio
display(d_end_i_bio)

                         Impacts - Individualist
﻿
Human health (DALY)                 3.474831e-05
Ecosystems (species.yr)             1.456560e-07

                         Impacts - Individualist
﻿
Human health (DALY)                 1.065235e-05
Ecosystems (species.yr)             4.478455e-08

                         Impacts - Individualist
﻿
Human health (DALY)                 4.333085e-05
Ecosystems (species.yr)             2.414959e-07

                         Impacts - Individualist
﻿
Human health (DALY)                 2.734399e-05
Ecosystems (species.yr)             1.466485e-07

**_Run the cell under to check the format of your answer(s)_**

In [58]:
assert (d_end_i_onetime.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_i_multuse.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_i_paper.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_i_bio.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_i_onetime.columns == ['Impacts - Individualist']).all(), 'The columns do not correspond'
assert (d_end_i_multuse.columns == ['Impacts - Individualist']).all(), 'The columns do not correspond'
assert (d_end_i_paper.columns == ['Impacts - Individualist']).all(), 'The columns do not correspond'
assert (d_end_i_bio.columns == ['Impacts - Individualist']).all(), 'The columns do not correspond'

Calculate the endpoint impacts for egalitarian perspective for the total number of used bags over 1 year for each type of bag: `d_end_e_onetime`, `d_end_e_multuse`, `d_end_e_paper` and `d_end_e_bio`.

In [59]:
d_end_e_onetime = P_e @ d_mid_e_onetime
display(d_end_e_onetime)

d_end_e_multuse = P_e @ d_mid_e_multuse
display(d_end_e_multuse)

d_end_e_paper = P_e @ d_mid_e_paper
display(d_end_e_paper)

d_end_e_bio = P_e @ d_mid_e_bio
display(d_end_e_bio)

                         Impacts - Egalitarian
﻿
Human health (DALY)               6.905229e-05
Ecosystems (species.yr)           3.001236e-07

                         Impacts - Egalitarian
﻿
Human health (DALY)               2.021653e-05
Ecosystems (species.yr)           8.709688e-08

                         Impacts - Egalitarian
﻿
Human health (DALY)               7.737229e-05
Ecosystems (species.yr)           3.760412e-07

                         Impacts - Egalitarian
﻿
Human health (DALY)               5.697538e-05
Ecosystems (species.yr)           2.763281e-07

**_Run the cell under to check the format of your answer(s)_**

In [60]:
assert (d_end_e_onetime.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_e_multuse.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_e_paper.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_e_bio.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_e_onetime.columns == ['Impacts - Egalitarian']).all(), 'The columns do not correspond'
assert (d_end_e_multuse.columns == ['Impacts - Egalitarian']).all(), 'The columns do not correspond'
assert (d_end_e_paper.columns == ['Impacts - Egalitarian']).all(), 'The columns do not correspond'
assert (d_end_e_bio.columns == ['Impacts - Egalitarian']).all(), 'The columns do not correspond'

Calculate the endpoint impacts for hierarchist perspective for the total number of used bags over 1 year for each type of bag: `d_end_h_onetime`, `d_end_h_multuse`, `d_end_h_paper` and `d_end_h_bio`.

In [61]:
d_end_h_onetime = P_h @ d_mid_h_onetime
display(d_end_h_onetime)

d_end_h_multuse = P_h @ d_mid_h_multuse
display(d_end_h_multuse)

d_end_h_paper = P_h @ d_mid_h_paper
display(d_end_h_paper)

d_end_h_bio = P_h @ d_mid_h_bio
display(d_end_h_bio)

                         Impacts - Hierarchist
﻿
Human health (DALY)               3.642257e-05
Ecosystems (species.yr)           1.332028e-07

                         Impacts - Hierarchist
﻿
Human health (DALY)               1.081081e-05
Ecosystems (species.yr)           3.904244e-08

                         Impacts - Hierarchist
﻿
Human health (DALY)               3.915703e-05
Ecosystems (species.yr)           1.817766e-07

                         Impacts - Hierarchist
﻿
Human health (DALY)               2.756104e-05
Ecosystems (species.yr)           1.261512e-07

**_Run the cell under to check the format of your answer(s)_**

In [62]:
assert (d_end_h_onetime.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_h_multuse.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_h_paper.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_h_bio.index == ['Human health (DALY)', 'Ecosystems (species.yr)']).all(), 'The index do not correspond'
assert (d_end_h_onetime.columns == ['Impacts - Hierarchist']).all(), 'The columns do not correspond'
assert (d_end_h_multuse.columns == ['Impacts - Hierarchist']).all(), 'The columns do not correspond'
assert (d_end_h_paper.columns == ['Impacts - Hierarchist']).all(), 'The columns do not correspond'
assert (d_end_h_bio.columns == ['Impacts - Hierarchist']).all(), 'The columns do not correspond'

Which option performs better regarding ecosystems in the individualist perspective? Will the conclusion change if we look at the egalitarian perspective?

1. One-time PE bag
2. Multiple-use PE bag
3. Paper bag
4. Biodegradable bag

Define your answer as the variables `answer_7b_ECO_indiv` and `answer_7b_ECO_egal`. Your answer should be `answer_7b_ECO_indiv = {1}` if you think the "1. One-time PE bag" performs best for ecosystems in individualist perspective.

In [63]:
answer_7b_ECO_indiv = {2}
answer_7b_ECO_egal = {2}

**_Run the cell under to check the format of your answer(s)_**

In [64]:
assert all (type(i) in [set] for i in [answer_7b_ECO_indiv, answer_7b_ECO_egal]), 'The answer(s) must be a set of values'